# Reference: https://golangci-lint.run/docs/configuration/file/

version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errchkjson
    - exhaustive
    - funcorder
#    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - mirror
    - misspell
    - nakedret
#    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    gomoddirectives:
      toolchain-forbidden: true
    nolintlint:
      require-specific: true
      require-explanation: true

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Relax requirements for tests.
      - linters:
          - goconst
          - noctx
        path: _test.go
      - linters:
          - golint
          - stylecheck
          - revive
        text: "error strings should not be capitalized"
      # TODO: fix this later.
      - linters:
          - revive
        text: "^unused-parameter"

formatters:
  enable:
    - gci
    - gofmt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/hypnoglow/helm-s3)

issues:
  fix: true

run:
  timeout: 5m
  build-tags: []
