builds:
  - main: ./cmd/helms3
    binary: ./bin/helms3
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - windows_amd64

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml
