name: "s3"
version: "0.13.0"
usage: "Manage chart repositories on Amazon S3"
description: |-
  Provides AWS S3 protocol support for charts and repos. https://github.com/hypnoglow/helm-s3
command: "$HELM_PLUGIN_DIR/bin/helms3"
downloaders:
- command: "bin/helms3"
  protocols:
    - "s3"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
